# Generated by Django 5.2.13 on 2026-05-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_feepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
